# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sportsMy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sportsMy

  pod 'AMap3DMap' #3D地图SDK
 pod 'AMapSearch' #搜索服务SDK

end
